# Generated by Django 4.0.3 on 2022-03-13 12:34

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', djrichtextfield.models.RichTextField(verbose_name='belgi')),
                ('title', models.CharField(max_length=150, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='matn')),
            ],
            options={
                'verbose_name': 'Sabab',
                'verbose_name_plural': 'Sabablar',
            },
        ),
        migrations.CreateModel(
            name='Client_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client feedback/', verbose_name='rasm')),
                ('name', models.CharField(max_length=150, verbose_name='ism')),
                ('feedback', models.TextField(verbose_name='fikr')),
            ],
            options={
                'verbose_name': 'Mijoz fikri',
                'verbose_name_plural': 'Mijoz fikrlari',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malumotlar', verbose_name='rasm')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='matn')),
            ],
            options={
                'verbose_name': 'Malumot',
                'verbose_name_plural': 'Malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='rasm')),
                ('title', models.CharField(max_length=100, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='matn')),
                ('price', models.PositiveIntegerField(verbose_name='narh')),
            ],
            options={
                'verbose_name': 'Mahsulotlar',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='video_background', verbose_name='orqa fon')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='matn')),
                ('video', models.FileField(upload_to='video/', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='matn'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100, verbose_name='sarlavha'),
        ),
    ]
