# Generated by Django 4.0.3 on 2022-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cause_client_feedback_information_products_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='icon',
            field=models.CharField(max_length=200, verbose_name='belgi'),
        ),
    ]
