# Generated by Django 4.0.3 on 2022-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cause_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'verbose_name': 'Bizning yutuqlarimiz', 'verbose_name_plural': 'Bizning yutuqlarimiz'},
        ),
        migrations.RemoveField(
            model_name='cause',
            name='icon',
        ),
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ImageField(default=1, upload_to='causes/', verbose_name='rasm'),
            preserve_default=False,
        ),
    ]
