# Generated by Django 4.0.3 on 2022-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cause_options_alter_information_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveIntegerField()),
            ],
        ),
    ]
